/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Luciano
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Principal
     */
    public TelaPrincipal() {
        initComponents();
        this.setUndecorated(true);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Perfil = new javax.swing.JLabel();
        lbl_Usuario = new javax.swing.JLabel();
        lbl_Data = new javax.swing.JLabel();
        btn_Sair = new javax.swing.JButton();
        Desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        txt_ID = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_Chamados = new javax.swing.JMenuItem();
        menu_Usuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menu_Sair = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuInfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cotrole de Chamados do TI");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lbl_Perfil.setText("Perfil");

        lbl_Usuario.setText("Usuário");

        lbl_Data.setText("Data");

        btn_Sair.setText("Sair ( F1 )");
        btn_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SairActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lsj/imagens/Logo_2.png"))); // NOI18N

        Desktop.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DesktopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(51, 51, 51))
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DesktopLayout.createSequentialGroup()
                .addContainerGap(334, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        txt_ID.setText("ID");

        jMenu1.setText("Cadastro");

        menu_Chamados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        menu_Chamados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lsj/icones/ic_phone_32_px.png"))); // NOI18N
        menu_Chamados.setText("Chamados");
        menu_Chamados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ChamadosActionPerformed(evt);
            }
        });
        jMenu1.add(menu_Chamados);

        menu_Usuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        menu_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lsj/icones/ic_user_32_px.png"))); // NOI18N
        menu_Usuario.setText("Usuários");
        menu_Usuario.setEnabled(false);
        menu_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_UsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(menu_Usuario);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opções");

        menu_Sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menu_Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lsj/icones/ic_ext.png"))); // NOI18N
        menu_Sair.setText("Sair");
        menu_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_SairActionPerformed(evt);
            }
        });
        jMenu2.add(menu_Sair);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ajuda");

        menuInfo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        menuInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lsj/icones/ic_inf_32_px.png"))); // NOI18N
        menuInfo.setText("Informações");
        menuInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInfoActionPerformed(evt);
            }
        });
        jMenu3.add(menuInfo);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(txt_ID)
                .addGap(18, 18, 18)
                .addComponent(lbl_Perfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 535, Short.MAX_VALUE)
                .addComponent(lbl_Data)
                .addGap(123, 123, 123)
                .addComponent(btn_Sair))
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_Data)
                        .addComponent(btn_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_Perfil)
                        .addComponent(lbl_Usuario)
                        .addComponent(txt_ID)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Desktop))
        );

        setSize(new java.awt.Dimension(883, 594));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menu_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_UsuarioActionPerformed
        Tela_Usuarios usuario = new Tela_Usuarios();
        usuario.setVisible(true);
        Desktop.add(usuario);
    }//GEN-LAST:event_menu_UsuarioActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //As linha abaixo substitui a lebel Lbl_Data pela data atual do sistea ao inicializar o for
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.YEAR_FIELD);//Escolher formato da data

        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");
        Date hora = Calendar.getInstance().getTime();

        lbl_Data.setText(formatador.format(data) + " - " + sdf.format(hora));
    }//GEN-LAST:event_formWindowActivated

    private void btn_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SairActionPerformed
        //Exibe uma caixa de dialogo
        int sair = JOptionPane.showConfirmDialog(null, "Deseja Realmente Sair?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_SairActionPerformed

    private void menu_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_SairActionPerformed
        //Exibe uma caixa de dialogo
        int sair = JOptionPane.showConfirmDialog(null, "Deseja Realmente Sair?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_menu_SairActionPerformed

    private void menu_ChamadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ChamadosActionPerformed
        Tela_Chamado chamado = new Tela_Chamado();
        chamado.setVisible(true);
        Desktop.add(chamado);
    }//GEN-LAST:event_menu_ChamadosActionPerformed

    private void menuInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInfoActionPerformed
        Tela_Infor Info = new Tela_Infor();
        Info.setVisible(true);
        Desktop.add(Info);
    }//GEN-LAST:event_menuInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JButton btn_Sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JLabel lbl_Data;
    public static javax.swing.JLabel lbl_Perfil;
    public static javax.swing.JLabel lbl_Usuario;
    private javax.swing.JMenuItem menuInfo;
    public static javax.swing.JMenuItem menu_Chamados;
    private javax.swing.JMenuItem menu_Sair;
    public static javax.swing.JMenuItem menu_Usuario;
    public static javax.swing.JLabel txt_ID;
    // End of variables declaration//GEN-END:variables
}
