/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Usuarios;
import controller.Controller_User;
import javax.swing.BorderFactory;

/**
 *
 * @author Luciano
 */
public class Tela_Usuarios extends javax.swing.JInternalFrame {

    private JPanel painel_user;

    /**
     * Creates new form Tela_Usuarios
     */
    public Tela_Usuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_Nome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_Login = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_Senha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_Carco = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Setor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_Ramal = new javax.swing.JTextField();
        cbx_Perfil = new javax.swing.JComboBox<>();
        btn_Novo = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        btn_Pesquisar = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        btn_Alterar = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        btn_Excluir = new javax.swing.JToggleButton();
        txt_ID = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("ID:");

        txt_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_LoginActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        jLabel3.setText("Cargo:");

        jLabel4.setText("Setor:");

        jLabel5.setText("Ramal:");

        cbx_Perfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "user", "admin" }));

        btn_Novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lsj/icones/ic_Mais_User.png"))); // NOI18N
        btn_Novo.setToolTipText("Adicionar Usuário");
        btn_Novo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Novo.setMaximumSize(new java.awt.Dimension(87, 63));
        btn_Novo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_Novo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NovoActionPerformed(evt);
            }
        });

        jLabel6.setText("Perfil:");

        btn_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lsj/icones/ic_Consultar_User.png"))); // NOI18N
        btn_Pesquisar.setToolTipText("Consultar Usuário");
        btn_Pesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Pesquisar.setMaximumSize(new java.awt.Dimension(87, 63));
        btn_Pesquisar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_Pesquisar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PesquisarActionPerformed(evt);
            }
        });

        jLabel7.setText("Login:");

        btn_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lsj/icones/ic_Altera_User.png"))); // NOI18N
        btn_Alterar.setToolTipText("Alterar Cadastro");
        btn_Alterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Alterar.setMaximumSize(new java.awt.Dimension(87, 63));
        btn_Alterar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_Alterar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AlterarActionPerformed(evt);
            }
        });

        jLabel8.setText("Senha:");

        btn_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lsj/icones/ic_Excluir_User.png"))); // NOI18N
        btn_Excluir.setToolTipText("Excluir Cadastro");
        btn_Excluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Excluir.setMaximumSize(new java.awt.Dimension(87, 63));
        btn_Excluir.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_Excluir.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_Nome, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Carco, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 401, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbx_Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_Setor)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_Ramal, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Login)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Novo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbx_Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Carco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Setor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_Ramal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txt_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8)
                        .addComponent(txt_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Novo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Pesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Alterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(92, 92, 92))
        );

        setBounds(0, 0, 700, 441);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_LoginActionPerformed

    private void btn_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NovoActionPerformed
              txt_ID.setText("");
        if (!"".equals(txt_Nome.getText())
                && !"".equals(txt_Carco.getText())
                && !"".equals(txt_Setor.getText())
                && !"".equals(txt_Ramal.getText())
                && !"".equals(cbx_Perfil.getSelectedItem())
                && !"".equals(txt_Login.getText())
                && !"".equals(txt_Senha.getText())) {
            Usuarios obj_user = new Usuarios();

            obj_user.setNome(txt_Nome.getText());
            obj_user.setCargo(txt_Carco.getText());
            obj_user.setSetor(txt_Setor.getText());
            obj_user.setRamal(Integer.parseInt(txt_Ramal.getText()));
            obj_user.setPerfil(cbx_Perfil.getSelectedItem().toString());
            obj_user.setLogin(txt_Login.getText());
            obj_user.setSenha(txt_Senha.getText());

            if (txt_ID.getText().equals("")) {
                Controller_User dao = new Controller_User();
                // Chama o Método CadastraUsuario
                dao.cadastrarUsuario(obj_user);
            }
        } else {

            JOptionPane.showMessageDialog(null, "Preencha todos os campos.");
        }
    }//GEN-LAST:event_btn_NovoActionPerformed

    private void btn_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PesquisarActionPerformed
        String ID = txt_ID.getText();
        Usuarios obj_user = new Usuarios();

        Controller_User dao = new Controller_User();
        obj_user = dao.consultarporID(ID);
        if (txt_ID.getText() != null) {

            txt_Nome.setText(obj_user.getNome());
            txt_Carco.setText(obj_user.getCargo());
            txt_Setor.setText(obj_user.getSetor());
            txt_Ramal.setText(String.valueOf(obj_user.getRamal()));
            cbx_Perfil.setSelectedItem(obj_user.getPerfil());
            txt_Login.setText(obj_user.getLogin());
            txt_Senha.setText(obj_user.getSenha());

        } else {

            JOptionPane.showMessageDialog(null, "Usuario não encontrado");
        }
    }//GEN-LAST:event_btn_PesquisarActionPerformed

    private void btn_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AlterarActionPerformed
        if (!"".equals(txt_Nome.getText())
                && !"".equals(txt_Carco.getText())
                && !"".equals(txt_Setor.getText())
                && !"".equals(txt_Ramal.getText())
                && !"".equals(cbx_Perfil.getSelectedItem())
                && !"".equals(txt_Login.getText())
                && !"".equals(txt_Senha.getText())) {
            Usuarios obj_user = new Usuarios();

            obj_user.setNome(txt_Nome.getText());
            obj_user.setCargo(txt_Carco.getText());
            obj_user.setSetor(txt_Setor.getText());
            obj_user.setRamal(Integer.parseInt(txt_Ramal.getText()));
            obj_user.setPerfil(cbx_Perfil.getSelectedItem().toString());
            obj_user.setLogin(txt_Login.getText());
            obj_user.setSenha(txt_Senha.getText());
            obj_user.setID(Integer.parseInt(txt_ID.getText()));

            if (!txt_ID.getText().equals("")) {
                Controller_User dao = new Controller_User();
                // Chama o Método CadastraUsuario
                dao.alterarUsuario(obj_user);
            }
        } else {

            JOptionPane.showMessageDialog(null, "Preencha todos os campos.");
        }
    }//GEN-LAST:event_btn_AlterarActionPerformed

    private void btn_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExcluirActionPerformed
           if(txt_ID.getText().equals("")){
         
         JOptionPane.showMessageDialog(null, "Usuário não selecionado");
         
     }    else {
       
         
         int resposta = JOptionPane.OK_CANCEL_OPTION;
         int confirma = JOptionPane.showConfirmDialog(null, "Deseja Realmente Excluir o Usuário", "Atenção", JOptionPane.YES_NO_OPTION);
         if (confirma == JOptionPane.YES_OPTION) {
             
                Usuarios obj_user = new Usuarios();

        obj_user.setID(Integer.parseInt(txt_ID.getText()));

           Controller_User dao = new Controller_User();
                dao.excluirUsuario(obj_user); 

         
         }
           }
    }//GEN-LAST:event_btn_ExcluirActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
           Controller_User bt = new Controller_User();
           bt.Controller_Boton(); 
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JToggleButton btn_Alterar;
    public static javax.swing.JToggleButton btn_Excluir;
    public static javax.swing.JToggleButton btn_Novo;
    public static javax.swing.JToggleButton btn_Pesquisar;
    private javax.swing.JComboBox<String> cbx_Perfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txt_Carco;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_Login;
    private javax.swing.JTextField txt_Nome;
    private javax.swing.JTextField txt_Ramal;
    private javax.swing.JTextField txt_Senha;
    private javax.swing.JTextField txt_Setor;
    // End of variables declaration//GEN-END:variables
}
